name: mixer
version: 0.1.1
description: A mixer command-line application created by dcli
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  args: ^2.3.1
  collection: ^1.16.0
  dcli: ^3.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  path: ^1.8.3
  riverpod: ^2.4.0
  shutdown: ^0.4.3
  yaml: ^3.1.1
  
dev_dependencies: 
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lint_hard: ^4.0.0

dependecy_overrides:
  win: ^5.0.0