name: mixer
version: 0.0.1
description: A mixer command-line application created by dcli
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  args: ^2.3.1
  dcli: 1.33.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  riverpod: ^1.0.3
  shutdown: ^0.4.3
  
dev_dependencies: 
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lint_hard: ^1.0.0
