name: Release Android Build
on:
  push:
    tags:
      - v*
      - v0.*

jobs: 
  Build-And-Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 3.2.0

      - name: Install dependencies
        run: dart pub get

      - name: Build runner
        run: dart pub run build_runner build --delete-conflicting-outputs

      - name: Compile application
        run: dart compile exe bin/mixer.dart -o mixer

      - name: Create GH release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: mixer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}